#!/bin/bash
set -euxo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"

bash "$HERE/m4.sh"
bash "$HERE/ncurses.sh"
bash "$HERE/bash.sh"
bash "$HERE/coreutils.sh"
bash "$HERE/diffutils.sh"
bash "$HERE/file.sh"
bash "$HERE/findutils.sh"
bash "$HERE/gawk.sh"
bash "$HERE/grep.sh"
bash "$HERE/gzip.sh"
bash "$HERE/make.sh"
bash "$HERE/patch.sh"
bash "$HERE/sed.sh"
bash "$HERE/tar.sh"
bash "$HERE/xz.sh"
bash "$HERE/binutils-pass2.sh"
bash "$HERE/gcc-pass2.sh"
